In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('PHL_Building_Dataset_Recommendation_Mini.csv')
df = df[:25000]
df

,basements,central_air,exterior_condition,fireplaces,garage_type,interior_condition,market_value,number_of_rooms,number_stories,parcel_shape,street_designation,topography,total_area,total_livable_area,type_heater,view_type,building_description,section
0,0,Y,4.0,0.0,A,4.0,257500.0,6.0,2.0,E,ST,6,2625.30,1266.0,H,I,MASONRY,South
1,0,Y,4.0,0.0,A,4.0,249400.0,6.0,2.0,E,ST,6,1622.70,1266.0,A,I,MASONRY,South
2,0,Y,4.0,0.0,A,4.0,249500.0,6.0,2.0,E,ST,6,1624.50,1266.0,A,I,MASONRY,South
3,0,Y,4.0,0.0,A,4.0,249500.0,6.0,2.0,E,ST,6,1627.20,1266.0,H,I,MASONRY,South
4,0,Y,4.0,0.0,A,4.0,253800.0,6.0,2.0,E,ST,6,1683.90,1310.0,H,I,MASONRY,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24996,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,A,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24997,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24998,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24999,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1889.18,1274.0,B,I,MASONRY,North

In [3]:
df2 = pd.read_csv('PHL_Building_Dataset_Recommendation_Big.csv')
df2 = df2.reset_index()

In [4]:
df2['basements'] = df2['basements'].replace({'0': 'None', 'A' : 'Full Finished', 'B' : 'Full Semi-Finished', 
                                             'C' : 'Full Unfinished', 'D' : 'Full', 'E' : 'Partial Finished',
                                             'F' : 'Partial Semi-Finished', 'G' : 'Partial Unfinished',
                                             'H' : 'Partial - Unknown Finish', 'I' : 'Unknown Size - Finished',
                                             'J' : 'Unknown Size - Unfinished'})

df2['central_air'] = df2['central_air'].replace({'Y' : 'Yes', 'N' : 'No'})

df2['exterior_condition'] = df2['exterior_condition'].replace({0 : 'Not Applicable', 2 : 'Newer Construction / Rehabbed', 
                                                               3 : 'Above Average',
                                                               4 : 'Average', 5 : 'Below Average', 6 : 'Vacant',
                                                               7 : 'Sealed / Structurally Compromised'})

df2['garage_type'] = df2['garage_type'].replace({'0' : 'None', 'A' : 'Basement / Built-In','B' : 'Attached Garage',
                                                 'C' : 'Detached Garage', 'F' : 'Converted',
                                                 'S' : 'Self Park', 'T' : 'Attendant'})

df2['interior_condition'] = df2['interior_condition'].replace({0 : 'Not Applicable', 2 : 'Newer Construction / Rehabbed',
                                                               3 : 'Above Average', 4 : 'Average',
                                                               5 : 'Below Average', 6 : 'Vacant', 
                                                               7 : 'Sealed / Structurally Compromised'})

df2['parcel_shape'] = df2['parcel_shape'].replace({'A' : 'Irregular', 'B' : 'Grossly Irregular',
                                                   'C' : 'Triangular', 'D' : 'Right of way', 'E' : 'Rectangular'})

df2['street_designation'] = df2['street_designation'].replace({'AVE' : 'Avenue', 'BLV' : 'Boulevard', 'CIR' : 'Circle',
                                                               'CT ' : 'Court', 'DR ' : 'Drive', 'LA ' : 'Lane',
                                                               'MEW' : 'Mews', 'PK ' : 'Park', 'PKY' : 'Parkway',
                                                               'PL ' : 'Place', 'PLZ' : 'Plaza', 'RD ' : 'Road',
                                                               'ROW' : 'Roadway', 'SQ ' : 'Square', 'ST ' : 'Street', 
                                                               'TER' : 'Terrace'})

df2['topography'] = df2['topography'].replace({1 : 'Above Street Level', 2 : 'Below Street Level', 
                                               3 : 'Flood Plain', 4 : 'Rocky', 5 : 'Not identified', 
                                               6 : 'Level'})

df2['type_heater'] = df2['type_heater'].replace({'A':'Hot Air (Ducts)', 'B' :'Hot Water (Radiator or Baseboards)', 
                                                 'C' :'Electric Baseboard', 'D' :'Heat Pump', 'E' :'Other', 
                                                 'G' :'Radiant', 'H' : 'Undetermined', '0' : 'None'})

df2['view_type'] = df2['view_type'].replace({'I' : 'Typical', 'A' :'Cityscape', 'B' :'Flowing Water', 
                                             'C' : 'Park/Green Area', 'D' :'Commercial', 'E' :'Industrial', 
                                             'H' :'Edifice/Landmark', '0' : 'Not Applicable'})

df2['zoning'] = df2['zoning'].replace({1: 'RSA-5', 2:'RSA-4', 3:'RSA-3', 4 :'RSA-2', 5 : 'RSA-1', 
                                       6 :'RSD-3', 7 : 'RSD-2', 8 : 'RSD-1' })

In [5]:
game = [{'basements' : '0', 'central_air' : 'Y', 'exterior_condition' : 3,
        'fireplaces' : 1, 'garage_type' : 'A', 'interior_condition' : 3,
        'market_value' : 268503.7037037, 'number_of_rooms' : 10, 'number_stories' : 2, 
        'parcel_shape' : 'E', 'street_designation' : 'ST', 'topography' : 6, 
        'total_area' : 2000, 'total_livable_area' : 1500, 'type_heater' : 'H', 
        'view_type' : 'I', 'building_description' : 'MASONRY', 'section' : 'South'}]
new = pd.DataFrame(game)
df = df.append(new, ignore_index=True)
df

,basements,central_air,exterior_condition,fireplaces,garage_type,interior_condition,market_value,number_of_rooms,number_stories,parcel_shape,street_designation,topography,total_area,total_livable_area,type_heater,view_type,building_description,section
0,0,Y,4.0,0.0,A,4.0,257500.000000,6.0,2.0,E,ST,6,2625.30,1266.0,H,I,MASONRY,South
1,0,Y,4.0,0.0,A,4.0,249400.000000,6.0,2.0,E,ST,6,1622.70,1266.0,A,I,MASONRY,South
2,0,Y,4.0,0.0,A,4.0,249500.000000,6.0,2.0,E,ST,6,1624.50,1266.0,A,I,MASONRY,South
3,0,Y,4.0,0.0,A,4.0,249500.000000,6.0,2.0,E,ST,6,1627.20,1266.0,H,I,MASONRY,South
4,0,Y,4.0,0.0,A,4.0,253800.000000,6.0,2.0,E,ST,6,1683.90,1310.0,H,I,MASONRY,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24996,D,N,4.0,0.0,C,4.0,104500.000000,6.0,2.0,A,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24997,D,N,4.0,0.0,C,4.0,104500.000000,6.0,2.0,E,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24998,D,N,4.0,0.0,C,4.0,104500.000000,6.0,2.0,E,AVE,6,1888.00,1274.0,B,I,MASONRY,North
24999,D,N,4.0,0.0,C,4.0,104500.000000,6.0,2.0,E,AVE,6,1889.18,1274.0,B,I,MASONRY,North
25000,0,Y,3.0,1.0,A,3.0,268503.703704,10.0,2.0,E,ST,6,2000.00,1500.0,H,I,MASONRY,South

In [6]:
features = ["exterior_condition", "interior_condition", "market_value", "number_stories", "total_area", "total_livable_area", "building_description", "section"]

In [7]:
for i in df.columns:
    df[i] = df[i].astype('str')

In [8]:
def combo(x):
    return x["exterior_condition"] + " " + x["interior_condition"] + " " + x["market_value"] + " " + x["number_stories"] + " " + x["section"] + " " + x["building_description"] + " " + x["total_area"] + " " + x["total_livable_area"]

In [9]:
df['combo_features'] = df.apply(combo, axis=1)

In [10]:
df

,basements,central_air,exterior_condition,fireplaces,garage_type,interior_condition,market_value,number_of_rooms,number_stories,parcel_shape,street_designation,topography,total_area,total_livable_area,type_heater,view_type,building_description,section,combo_features
0,0,Y,4.0,0.0,A,4.0,257500.0,6.0,2.0,E,ST,6,2625.3,1266.0,H,I,MASONRY,South,4.0 4.0 257500.0 2.0 South MASONRY 2625.3 1266.0
1,0,Y,4.0,0.0,A,4.0,249400.0,6.0,2.0,E,ST,6,1622.7,1266.0,A,I,MASONRY,South,4.0 4.0 249400.0 2.0 South MASONRY 1622.7 1266.0
2,0,Y,4.0,0.0,A,4.0,249500.0,6.0,2.0,E,ST,6,1624.5,1266.0,A,I,MASONRY,South,4.0 4.0 249500.0 2.0 South MASONRY 1624.5 1266.0
3,0,Y,4.0,0.0,A,4.0,249500.0,6.0,2.0,E,ST,6,1627.2,1266.0,H,I,MASONRY,South,4.0 4.0 249500.0 2.0 South MASONRY 1627.2 1266.0
4,0,Y,4.0,0.0,A,4.0,253800.0,6.0,2.0,E,ST,6,1683.9,1310.0,H,I,MASONRY,South,4.0 4.0 253800.0 2.0 South MASONRY 1683.9 1310.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24996,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,A,AVE,6,1888.0,1274.0,B,I,MASONRY,North,4.0 4.0 104500.0 2.0 North MASONRY 1888.0 1274.0
24997,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1888.0,1274.0,B,I,MASONRY,North,4.0 4.0 104500.0 2.0 North MASONRY 1888.0 1274.0
24998,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1888.0,1274.0,B,I,MASONRY,North,4.0 4.0 104500.0 2.0 North MASONRY 1888.0 1274.0
24999,D,N,4.0,0.0,C,4.0,104500.0,6.0,2.0,E,AVE,6,1889.18,1274.0,B,I,MASONRY,North,4.0 4.0 104500.0 2.0 North MASONRY 1889.18 1274.0
25000,0,Y,3.0,1.0,A,3.0,268503.7037037,10.0,2.0,E,ST,6,2000.0,1500.0,H,I,MASONRY,South,3.0 3.0 268503.7037037 2.0 South MASONRY 2000....

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
CV = CountVectorizer()

In [13]:
property_matrix = CV.fit_transform(df['combo_features'])

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
cos_score = cosine_similarity(property_matrix)

In [16]:
similar_property = list(enumerate(cos_score[-1]))

In [17]:
similar_property[:6]

[(0, 0.36514837167011077),
 (1, 0.36514837167011077),
 (2, 0.36514837167011077),
 (3, 0.36514837167011077),
 (4, 0.36514837167011077),
 (5, 0.3333333333333334)]

In [18]:
sorted_property = sorted(similar_property, key=lambda x:x[1], reverse=True)[1:] # [1:] -> propertynya sendiri ga masuk

In [19]:
sorted_property[0]

(50, 0.5477225575051662)

In [20]:
print(f"Property Recommendation Based on Your Input :")
print("="*65)
count = 1
for i in sorted_property:
    print(count,". Residence Specification") 
    for j in range(1, 26):
        if j == 3:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "ft")
        elif j == 6:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "ft")
        elif j == 5:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "pcs")
        elif j == 10:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", "$",df2.iloc[i[0]][j])
        elif j == 11:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "rooms")
        elif j == 12:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "rooms")
        elif j == 13:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "rooms")
        elif j == 14:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "stories")
        elif j == 18:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "ft2")
        elif j == 19:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j], "ft2")
        else:
            print("    -", df2.columns[j].replace("_"," ").title() ,":", df2.iloc[i[0]][j])
    print("-"*65)
    count += 1
    if count == 6:
        break

Property Recommendation Based on Your Input :
=================================================================
1 . Residence Specification
    - Basements : Full
    - Central Air : No
    - Depth : 127.25 ft
    - Exterior Condition : Average
    - Fireplaces : 0.0 pcs
    - Frontage : 16.0 ft
    - Garage Type : None
    - Interior Condition : Average
    - Location : 1710 E MOYAMENSING AVE
    - Market Value : $ 274800.0
    - Number Of Bathrooms : 1.0 rooms
    - Number Of Bedrooms : 4.0 rooms
    - Number Of Rooms : 7.0 rooms
    - Number Stories : 2.0 stories
    - Parcel Shape : Rectangular
    - Street Designation : Avenue
    - Topography : Level
    - Total Area : 2036.0 ft2
    - Total Livable Area : 2000.0 ft2
    - Type Heater : Undetermined
    - View Type : Typical
    - Year Built : 1960.0
    - Zoning : RSA-5
    - Building Description : MASONRY
    - Section : South
-----------------------------------------------------------------
2 . Residence Specification
    - Basements : Full
    - Central Air : No
    - Depth : 72.0 ft
    - Exterior Condition : Average
    - Fireplaces : 0.0 pcs
    - Frontage : 24.0 ft
    - Garage Type : None
    - Interior Condition : Average
    - Location : 727 REED ST
    - Market Value : $ 272700.0
    - Number Of Bathrooms : 1.0 rooms
    - Number Of Bedrooms : 4.0 rooms
    - Number Of Rooms : 7.0 rooms
    - Number Stories : 2.0 stories
    - Parcel Shape : Rectangular
    - Street Designation : Street
    - Topography : Level
    - Total Area : 1728.0 ft2
    - Total Livable Area : 2000.0 ft2
    - Type Heater : Undetermined
    - View Type : Typical
    - Year Built : 1925.0
    - Zoning : RSA-5
    - Building Description : MASONRY
    - Section : South
-----------------------------------------------------------------
3 . Residence Specification
    - Basements : Partial Semi-Finished
    - Central Air : Yes
    - Depth : 60.0 ft
    - Exterior Condition : Above Average
    - Fireplaces : 1.0 pcs
    - Frontage : 25.0 ft
    - Garage Type : Basement / Built-In
    - Interior Condition : Above Average
    - Location : 2056-58 WAVERLY ST
    - Market Value : $ 1016100.0
    - Number Of Bathrooms : 2.0 rooms
    - Number Of Bedrooms : 3.0 rooms
    - Number Of Rooms : 7.0 rooms
    - Number Stories : 3.0 stories
    - Parcel Shape : Rectangular
    - Street Designation : Street
    - Topography : Above Street Level
    - Total Area : 1500.0 ft2
    - Total Livable Area : 2724.0 ft2
    - Type Heater : Hot Air (Ducts)
    - View Type : Typical
    - Year Built : 1750.0
    - Zoning : RSA-5
    - Building Description : MASONRY
    - Section : South
-----------------------------------------------------------------
4 . Residence Specification
    - Basements : Full Unfinished
    - Central Air : Yes
    - Depth : 110.0 ft
    - Exterior Condition : Average
    - Fireplaces : 0.0 pcs
    - Frontage : 16.0 ft
    - Garage Type : Detached Garage
    - Interior Condition : Average
    - Location : 1021 JACKSON ST
    - Market Value : $ 278500.0
    - Number Of Bathrooms : 1.0 rooms
    - Number Of Bedrooms : 4.0 rooms
    - Number Of Rooms : 7.0 rooms
    - Number Stories : 2.0 stories
    - Parcel Shape : Rectangular
    - Street Designation : Street
    - Topography : Level
    - Total Area : 1760.0 ft2
    - Total Livable Area : 2000.0 ft2
    - Type Heater : Hot Air (Ducts)
    - View Type : Typical
    - Year Built : 1925.0
    - Zoning : RSA-5
    - Building Description : MASONRY
    - Section : South
-----------------------------------------------------------------
5 . Residence Specification
    - Basements : Full
    - Central Air : No
    - Depth : 76.66 ft
    - Exterior Condition : Average
    - Fireplaces : 0.0 pcs
    - Frontage : 53.66 ft
    - Garage Type : Attached Garage
    - Interior Condition : Average
    - Location : 2611-15 S 5TH ST
    - Market Value : $ 189700.0
    - Number Of Bathrooms : 1.0 rooms
    - Number Of Bedrooms : 3.0 rooms
    - Number Of Rooms : 6.0 rooms
    - Number Stories : 2.0 stories
    - Parcel Shape : Rectangular
    - Street Designation : Street
    - Topography : Level
    - Total Area : 3970.84 ft2
    - Total Livable Area : 1500.0 ft2
    - Type Heater : Undetermined
    - View Type : Typical
    - Year Built : 1960.0
    - Zoning : RSA-5
    - Building Description : MASONRY
    - Section : South
-----------------------------------------------------------------